version: '2'

services:
  spark:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '7077:7077'
      - '8080:8080'
    networks:
      - datascience
  spark-worker:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - datascience
  nifi:
    image: apache/nifi:1.19.0
    ports:
      - '8443:8443'
    networks:
      - datascience
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=Admin@1qaz2wsx
    volumes:
      - ./nifi:/opt/nifi/nifi-current/demo

  zeppelin:
    image: apache/zeppelin:0.10.0
    ports:
      - '8081:8080'
    networks:
      - datascience

  # jupyter:
  #   image: jupyter/scipy-notebook:85f615d5cafa
  #   ports:
  #     - '10000:8888'
  #   networks:
  #     - datascience
      
networks:
  datascience:
    driver: bridge
